install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - nmake /f Makefile.vc

notifications:
  - provider: HipChat
    auth_token:
      secure: NtKXu/kGk8Td4YqCH95camAcNQtB3rMll+5DALAmbDY=
    room: dev
